services:
  db:
    image: postgres:{{ cookiecutter.postgresql_version }}
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env.test
    ports:
      - "5454:5432"
    networks:
      - {{ cookiecutter.repo_name }}
{%- if cookiecutter.use_websocket %}

  redis:
    image: redis:7
    ports:
      - "6363:6379"
    networks:
      - {{ cookiecutter.repo_name }}
{%- endif %}

volumes:
  dbdata:

networks:
  {{ cookiecutter.repo_name }}:
    driver: bridge
