src = ["{{ cookiecutter.package_name }}"]
target-version = "py311"

[lint]
ignore = ["E501", "F405"]
select = ["B", "C90", "E", "F", "I", "N", "N", "PL", "Q", "UP", "W"]

[lint.isort]
section-order = ["first-party", "future", "local-folder", "standard-library", "third-party"]
