services:
  db:
    image: postgres:{{ cookiecutter.postgresql_version }}
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - {{ cookiecutter.repo_name }}
{%- if cookiecutter.use_celery or cookiecutter.use_websocket %}

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - {{ cookiecutter.repo_name }}
{%- endif %}

volumes:
  dbdata:

networks:
  {{ cookiecutter.repo_name }}:
    driver: bridge
